<?php

/**
 * This is the model base class for the table "test".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Test".
 *
 * Columns in table "test" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $birthdate
 * @property string $birthtime
 * @property integer $enabled
 * @property string $status
 * @property string $slogan
 * @property string $content
 *
 */
abstract class BaseTest extends CActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'test';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Test|Tests', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, birthdate, birthtime, enabled, status, slogan, content', 'required'),
			array('enabled', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('status', 'length', 'max'=>9),
			array('id, name, birthdate, birthtime, enabled, status, slogan, content', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'birthdate' => Yii::t('app', 'Birthdate'),
			'birthtime' => Yii::t('app', 'Birthtime'),
			'enabled' => Yii::t('app', 'Enabled'),
			'status' => Yii::t('app', 'Status'),
			'slogan' => Yii::t('app', 'Slogan'),
			'content' => Yii::t('app', 'Content'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('birthdate', $this->birthdate, true);
		$criteria->compare('birthtime', $this->birthtime, true);
		$criteria->compare('enabled', $this->enabled);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('slogan', $this->slogan, true);
		$criteria->compare('content', $this->content, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}